name: Reusable Flow
on:
  workflow_call:
    inputs:
      workflow_name:
        required: false
        default: dist
        type: string
        description: "The name of the workflow to run"
    outputs:
      result:
        description: "The result of the workflow"
        value: ${{ jobs.deploy.outputs.outcome }}
  #   secrets:
  #    secret_name:
  #     required: false
  #    description: "A secret to pass to the workflow"
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.print-result.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.workflow_name  }}
      - name: Output files
        run: ls
      - name: Print result
        id: print-result
        run: echo "result=success" >> $GITHUB_OUTPUT
      - name: Output information
        run: echo "Deploying & uploading code"
